FORMAT: 1A
HOST: https://studyhub-server.azurewebsites.net/v1/


# Study Hub

This is the API documentation for StudyHub's backend server.

## User Registration [/auth/register]

### Register a user [POST]

You can create a user by sending a json request with an email and password. The
password must be eight characters or more.

+ Request (application/json)

        {
            "email": "example@gmail.com",
            "password": "12345678"
        }

+ Response 201 (application/json)

        {
            "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MDM0ODQ5OTYsImlhdCI6MTUwMzM5ODU4Niwic3ViIjo1fQ.GC6IEOohdo_xrz9__UeugIlir0qtJdKbEzBtLgqjt5A",
            "message": "Successfully registered",
            "status": "success"
        }
        
+ Request (application/json)

        {
            "email": "example@gmail",
            "password": "123456"
        }

+ Response 400 (application/json)

        {
            "message": "Missing or wrong email format or password is less than eight characters",
            "status": "failed"
        }
        
+ Request (application/json)

        {
            "email": "example@gmail.com",
            "password": "12345678"
        }
        
+ Response 409 (application/json)

        {
            "message": "Failed, User already exists, Please sign in",
            "status": "failed"
        }

## Login [/auth/login]

### Login a user [POST]
You can login a user by sending their email and password. Please take note
of the auth token for you will need it for all user requests.

+ Request (application/json)

        {
            "email": "example@gmail.com",
            "password": "12345678"
        }

+ Response 200 (application/json)

        {
            "auth_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1MDM0ODQ5OTYsImlhdCI6MTUwMzM5ODU4Niwic3ViIjo1fQ.GC6IEOohdo_xrz9__UeugIlir0qtJdKbEzBtLgqjt5A",
            "message": "Successfully logged in",
            "status": "success"
        }
        
+ Request (application/json)

        {
            "email": "example@gmail",
            "password": "123456"
        }

+ Response 400 (application/json)

        {
          "message": "Missing or wrong email format or password is less than eight characters",
          "status": "failed"
        }
        
+ Request (application/json)

        {
            "email": "example@gmail.com",
            "password": "wrong_password"
        }

+ Response 401 (application/json)

        {
          "message": "User does not exist or password is incorrect",
          "status": "failed"
        }

## Logout [/auth/logout]

### Log out a user [POST]

You can log out a user by sending a request with their email and address. The
auth token will then be invalidated.

+ Request (application/json)

    + Headers
    
            Authorization: Bearer JWT Token

+ Response 200 (application/json)

        {
            "message": "Successfully logged out",
            "status": "success"
        }
        
+ Request (application/json)


+ Response 400 (application/json)

        {
          "message": "Provide an authorization header",
          "status": "failed"
        }
        
+ Request (application/json)

    + Headers
    
            Authorization: Bearer Not_A_Token

+ Response 401 (application/json)

        {
          "message": "Provide a valid auth token",
          "status": "failed"
        }

+ Response 401 (application/json)

        {
          "message": "Signature expired, Please sign in again",
          "status": "failed"
        }

+ Response 401 (application/json)

        {
          "message": "Invalid token. Please sign in again",
          "status": "failed"
        }
        
## Reset Password [/auth/reset/password]

### Reset user password [POST]

Resetting the user's password requires them to be logged in. A request with their
authorization token, old password and new password must be made.

+ Request (application/json)

    + Body

            {
                "oldPassword": "12345678",
                "newPassword": "09876543",
                "passwordConfirmation": "09876543"
            }
        

    + Headers
    
            Authorization: Bearer JWT Token
            
+ Response 200 (application/json)

        {
            "message": "Password reset successfully",
            "status": "success"
        }
        
+ Request (application/json)

    + Body

            {
                "oldPassword": "12345678",
                "newPassword": "09876543",
                "passwordConfirmation": "19876543"
            }

    + Headers
    
            Authorization: Bearer JWT Token
            
+ Response 400 (application/json)

        {
            "message": "New Passwords do not match",
            "status": "failed"
        }
        
+ Request (application/json)

    + Body

            {
                "oldPassword": "12345678",
                "newPassword": "0987",
                "passwordConfirmation": "0987"
            }

    + Headers
    
            Authorization: Bearer JWT Token
            
+ Response 400 (application/json)

        {
            "message": "New password should be at least eight characters long",
            "status": "failed"
        }
        
+ Request (application/json)

    + Body

            
                "oldPassword": "wrong_password",
                "newPassword": "09876543",
                "passwordConfirmation": "09876543"
            }

    + Headers
    
            Authorization: Bearer JWT Token
            
+ Response 401 (application/json)

        {
            "message": "Incorrect password",
            "status": "failed"
        }